import type { Destination } from '@/data/destinations';

export type FlightInfo = {
  flightNumber: string;
  airline: string;
  origin: { iata: string; name: string; city: string };
  destination: Destination;
  departureTime: string;
  arrivalTime: string;
  aircraft: string;
  previousGate?: string;
};

type RouteRecord = Omit<FlightInfo, 'flightNumber'>;

// Global route table — keyed by flight number only, regardless of departure airport.
// Each entry carries its own origin so the engine can auto-set the airport.
const ROUTES: Record<string, RouteRecord> = {
  // ── Finnair (AY) departing HEL ──────────────────────────────────────────────
  'AY1':   { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LHR', city: 'London Heathrow',        country: 'United Kingdom', schengen: false }, departureTime: '08:15', arrivalTime: '10:25', aircraft: 'A350-900',  previousGate: '35' },
  'AY3':   { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LHR', city: 'London Heathrow',        country: 'United Kingdom', schengen: false }, departureTime: '13:40', arrivalTime: '15:50', aircraft: 'A321',      previousGate: '36' },
  'AY5':   { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LHR', city: 'London Heathrow',        country: 'United Kingdom', schengen: false }, departureTime: '18:05', arrivalTime: '20:20', aircraft: 'A321',      previousGate: '36' },
  'AY121': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LHR', city: 'London Heathrow',        country: 'United Kingdom', schengen: false }, departureTime: '10:30', arrivalTime: '12:45', aircraft: 'A321neo',   previousGate: '35' },
  'AY131': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LGW', city: 'London Gatwick',         country: 'United Kingdom', schengen: false }, departureTime: '07:05', arrivalTime: '09:10', aircraft: 'A320',      previousGate: '34' },
  'AY201': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'JFK', city: 'New York JFK',           country: 'United States',  schengen: false }, departureTime: '09:45', arrivalTime: '12:30', aircraft: 'A350-900',  previousGate: '52' },
  'AY203': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'JFK', city: 'New York JFK',           country: 'United States',  schengen: false }, departureTime: '16:30', arrivalTime: '19:15', aircraft: 'A350-900',  previousGate: '51' },
  'AY211': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'ORD', city: "Chicago O'Hare",         country: 'United States',  schengen: false }, departureTime: '11:15', arrivalTime: '13:10', aircraft: 'A350-900',  previousGate: '53' },
  'AY221': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'MIA', city: 'Miami',                  country: 'United States',  schengen: false }, departureTime: '14:25', arrivalTime: '18:50', aircraft: 'A330-300',  previousGate: '50' },
  'AY231': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'LAX', city: 'Los Angeles',            country: 'United States',  schengen: false }, departureTime: '10:00', arrivalTime: '14:30', aircraft: 'A350-900',  previousGate: '52' },
  'AY401': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'BKK', city: 'Bangkok',                country: 'Thailand',       schengen: false }, departureTime: '11:30', arrivalTime: '01:25', aircraft: 'A350-900',  previousGate: '53' },
  'AY403': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'BKK', city: 'Bangkok',                country: 'Thailand',       schengen: false }, departureTime: '22:10', arrivalTime: '12:05', aircraft: 'A350-900',  previousGate: '54' },
  'AY601': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'NRT', city: 'Tokyo Narita',           country: 'Japan',          schengen: false }, departureTime: '14:45', arrivalTime: '07:10', aircraft: 'A350-900',  previousGate: '51' },
  'AY603': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'HND', city: 'Tokyo Haneda',           country: 'Japan',          schengen: false }, departureTime: '22:30', arrivalTime: '14:55', aircraft: 'A350-900',  previousGate: '55' },
  'AY701': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'SIN', city: 'Singapore',              country: 'Singapore',      schengen: false }, departureTime: '23:55', arrivalTime: '16:55', aircraft: 'A350-900',  previousGate: '52' },
  'AY711': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'DXB', city: 'Dubai',                  country: 'UAE',            schengen: false }, departureTime: '21:40', arrivalTime: '04:05', aircraft: 'A330-300',  previousGate: '50' },
  'AY721': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'HKG', city: 'Hong Kong',              country: 'Hong Kong',      schengen: false }, departureTime: '22:45', arrivalTime: '14:30', aircraft: 'A350-900',  previousGate: '53' },
  'AY801': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'PEK', city: 'Beijing',                country: 'China',          schengen: false }, departureTime: '23:15', arrivalTime: '11:40', aircraft: 'A350-900',  previousGate: '54' },
  'AY841': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'PVG', city: 'Shanghai',               country: 'China',          schengen: false }, departureTime: '22:35', arrivalTime: '11:15', aircraft: 'A350-900',  previousGate: '55' },
  'AY861': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'ICN', city: 'Seoul Incheon',          country: 'South Korea',    schengen: false }, departureTime: '00:10', arrivalTime: '15:20', aircraft: 'A350-900',  previousGate: '51' },
  'AY901': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'DEL', city: 'Delhi',                  country: 'India',          schengen: false }, departureTime: '20:30', arrivalTime: '06:25', aircraft: 'A330-300',  previousGate: '50' },
  'AY921': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'BOM', city: 'Mumbai',                 country: 'India',          schengen: false }, departureTime: '21:15', arrivalTime: '07:50', aircraft: 'A330-300',  previousGate: '50' },
  'AY511': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'ARN', city: 'Stockholm Arlanda',      country: 'Sweden',         schengen: true  }, departureTime: '07:20', arrivalTime: '08:05', aircraft: 'ATR 72',    previousGate: '14' },
  'AY521': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'CPH', city: 'Copenhagen',             country: 'Denmark',        schengen: true  }, departureTime: '08:00', arrivalTime: '09:20', aircraft: 'A320',      previousGate: '13' },
  'AY531': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'OSL', city: 'Oslo Gardermoen',        country: 'Norway',         schengen: true  }, departureTime: '08:45', arrivalTime: '10:20', aircraft: 'A320',      previousGate: '15' },
  'AY541': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'AMS', city: 'Amsterdam',              country: 'Netherlands',    schengen: true  }, departureTime: '09:30', arrivalTime: '11:50', aircraft: 'A321',      previousGate: '12' },
  'AY551': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'CDG', city: 'Paris Charles de Gaulle',country: 'France',         schengen: true  }, departureTime: '10:15', arrivalTime: '13:00', aircraft: 'A321',      previousGate: '13' },
  'AY561': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'FRA', city: 'Frankfurt',              country: 'Germany',        schengen: true  }, departureTime: '07:50', arrivalTime: '10:10', aircraft: 'A321',      previousGate: '21' },
  'AY571': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'MUC', city: 'Munich',                 country: 'Germany',        schengen: true  }, departureTime: '06:35', arrivalTime: '08:45', aircraft: 'A320',      previousGate: '11' },
  'AY581': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'BER', city: 'Berlin Brandenburg',     country: 'Germany',        schengen: true  }, departureTime: '11:00', arrivalTime: '12:55', aircraft: 'A320',      previousGate: '12' },
  'AY591': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'ZRH', city: 'Zurich',                 country: 'Switzerland',    schengen: true  }, departureTime: '09:05', arrivalTime: '11:15', aircraft: 'A320',      previousGate: '22' },
  'AY640': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'VIE', city: 'Vienna',                 country: 'Austria',        schengen: true  }, departureTime: '08:20', arrivalTime: '10:15', aircraft: 'A320',      previousGate: '16' },
  'AY650': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'FCO', city: 'Rome Fiumicino',         country: 'Italy',          schengen: true  }, departureTime: '10:55', arrivalTime: '14:10', aircraft: 'A321',      previousGate: '19' },
  'AY660': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'BCN', city: 'Barcelona',              country: 'Spain',          schengen: true  }, departureTime: '12:30', arrivalTime: '16:00', aircraft: 'A321',      previousGate: '17' },
  'AY670': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'MAD', city: 'Madrid',                 country: 'Spain',          schengen: true  }, departureTime: '11:45', arrivalTime: '15:40', aircraft: 'A321',      previousGate: '18' },
  'AY680': { airline: 'Finnair', origin: { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki' },  destination: { iata: 'ATH', city: 'Athens',                 country: 'Greece',         schengen: true  }, departureTime: '13:10', arrivalTime: '17:30', aircraft: 'A321',      previousGate: '20' },

  // ── British Airways (BA) departing LHR ──────────────────────────────────────
  'BA001':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'JFK', city: 'New York JFK',   country: 'United States',  schengen: false }, departureTime: '11:00', arrivalTime: '14:00', aircraft: 'B777-300ER', previousGate: '502' },
  'BA003':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'JFK', city: 'New York JFK',   country: 'United States',  schengen: false }, departureTime: '14:00', arrivalTime: '17:00', aircraft: 'B777-300ER', previousGate: '511' },
  'BA007':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'LAX', city: 'Los Angeles',    country: 'United States',  schengen: false }, departureTime: '12:45', arrivalTime: '16:00', aircraft: 'B777-200ER' },
  'BA009':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'ORD', city: "Chicago O'Hare", country: 'United States',  schengen: false }, departureTime: '13:30', arrivalTime: '16:30', aircraft: 'B777-200ER' },
  'BA011':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'BOS', city: 'Boston',         country: 'United States',  schengen: false }, departureTime: '14:30', arrivalTime: '17:15', aircraft: 'B767-300' },
  'BA031':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'DXB', city: 'Dubai',          country: 'UAE',            schengen: false }, departureTime: '21:30', arrivalTime: '08:10', aircraft: 'B777-300ER' },
  'BA015':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'SIN', city: 'Singapore',      country: 'Singapore',      schengen: false }, departureTime: '23:55', arrivalTime: '17:45', aircraft: 'B777-300ER' },
  'BA027':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'HKG', city: 'Hong Kong',      country: 'Hong Kong',      schengen: false }, departureTime: '21:15', arrivalTime: '16:15', aircraft: 'B777-300ER' },
  'BA005':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'NRT', city: 'Tokyo Narita',   country: 'Japan',          schengen: false }, departureTime: '12:00', arrivalTime: '08:35', aircraft: 'B787-9' },
  'BA043':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'YYZ', city: 'Toronto',        country: 'Canada',         schengen: false }, departureTime: '13:00', arrivalTime: '15:30', aircraft: 'B767-300' },
  'BA304':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'CDG', city: 'Paris',          country: 'France',         schengen: false }, departureTime: '06:30', arrivalTime: '08:55', aircraft: 'A320' },
  'BA430':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'AMS', city: 'Amsterdam',      country: 'Netherlands',    schengen: false }, departureTime: '07:15', arrivalTime: '09:30', aircraft: 'A319' },
  'BA462':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'FRA', city: 'Frankfurt',      country: 'Germany',        schengen: false }, departureTime: '07:00', arrivalTime: '09:55', aircraft: 'A321' },
  'BA466':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'MAD', city: 'Madrid',         country: 'Spain',          schengen: false }, departureTime: '08:30', arrivalTime: '12:00', aircraft: 'A320' },
  'BA548':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'FCO', city: 'Rome',           country: 'Italy',          schengen: false }, departureTime: '09:30', arrivalTime: '13:15', aircraft: 'A319' },
  'BA852':  { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'HEL', city: 'Helsinki',       country: 'Finland',        schengen: false }, departureTime: '13:20', arrivalTime: '18:25', aircraft: 'A320' },
  'BA1466': { airline: 'British Airways', origin: { iata: 'LHR', name: 'London Heathrow', city: 'London' }, destination: { iata: 'ATH', city: 'Athens',         country: 'Greece',         schengen: false }, departureTime: '10:15', arrivalTime: '15:50', aircraft: 'A320' },

  // ── KLM (KL) departing AMS ───────────────────────────────────────────────────
  'KL601':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'JFK', city: 'New York JFK',  country: 'United States', schengen: false }, departureTime: '09:15', arrivalTime: '11:45', aircraft: 'B777-200ER' },
  'KL603':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'JFK', city: 'New York JFK',  country: 'United States', schengen: false }, departureTime: '14:15', arrivalTime: '16:30', aircraft: 'B787-9' },
  'KL605':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'LAX', city: 'Los Angeles',   country: 'United States', schengen: false }, departureTime: '11:35', arrivalTime: '14:00', aircraft: 'B777-200ER' },
  'KL685':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'DXB', city: 'Dubai',         country: 'UAE',           schengen: false }, departureTime: '21:00', arrivalTime: '05:15', aircraft: 'B777-200ER' },
  'KL835':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'SIN', city: 'Singapore',     country: 'Singapore',     schengen: false }, departureTime: '23:40', arrivalTime: '17:15', aircraft: 'B777-300ER' },
  'KL887':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'NRT', city: 'Tokyo Narita',  country: 'Japan',         schengen: false }, departureTime: '12:30', arrivalTime: '08:10', aircraft: 'B777-200ER' },
  'KL641':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'YYZ', city: 'Toronto',       country: 'Canada',        schengen: false }, departureTime: '10:45', arrivalTime: '12:30', aircraft: 'B767-300' },
  'KL1009': { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'LHR', city: 'London Heathrow',country: 'United Kingdom',schengen: false }, departureTime: '07:00', arrivalTime: '07:15', aircraft: 'Embraer 175' },
  'KL727':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'ARN', city: 'Stockholm',     country: 'Sweden',        schengen: true  }, departureTime: '07:30', arrivalTime: '09:20', aircraft: 'Embraer 190' },
  'KL743':  { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'CPH', city: 'Copenhagen',    country: 'Denmark',       schengen: true  }, departureTime: '08:00', arrivalTime: '09:25', aircraft: 'Embraer 175' },
  'KL1131': { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'FRA', city: 'Frankfurt',     country: 'Germany',       schengen: true  }, departureTime: '06:40', arrivalTime: '07:55', aircraft: 'Embraer 175' },
  'KL1229': { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'CDG', city: 'Paris',         country: 'France',        schengen: true  }, departureTime: '07:20', arrivalTime: '08:45', aircraft: 'Embraer 175' },
  'KL1697': { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'MAD', city: 'Madrid',        country: 'Spain',         schengen: true  }, departureTime: '09:00', arrivalTime: '11:30', aircraft: 'A319' },
  'KL1113': { airline: 'KLM', origin: { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' }, destination: { iata: 'HEL', city: 'Helsinki',      country: 'Finland',       schengen: true  }, departureTime: '09:30', arrivalTime: '12:15', aircraft: 'Embraer 175' },

  // ── SAS (SK) departing ARN ───────────────────────────────────────────────────
  'SK901': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'JFK', city: 'New York JFK',  country: 'United States', schengen: false }, departureTime: '10:30', arrivalTime: '12:45', aircraft: 'A330-300' },
  'SK903': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'LAX', city: 'Los Angeles',   country: 'United States', schengen: false }, departureTime: '12:00', arrivalTime: '14:30', aircraft: 'A330-300' },
  'SK085': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'LHR', city: 'London Heathrow',country: 'United Kingdom',schengen: false }, departureTime: '07:05', arrivalTime: '08:30', aircraft: 'A320' },
  'SK089': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'LHR', city: 'London Heathrow',country: 'United Kingdom',schengen: false }, departureTime: '16:55', arrivalTime: '18:20', aircraft: 'A320' },
  'SK995': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'DXB', city: 'Dubai',         country: 'UAE',           schengen: false }, departureTime: '22:00', arrivalTime: '06:15', aircraft: 'A330-300' },
  'SK999': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'BKK', city: 'Bangkok',       country: 'Thailand',      schengen: false }, departureTime: '22:30', arrivalTime: '14:00', aircraft: 'A330-300' },
  'SK729': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'CPH', city: 'Copenhagen',    country: 'Denmark',       schengen: true  }, departureTime: '06:15', arrivalTime: '07:25', aircraft: 'A319' },
  'SK731': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'CPH', city: 'Copenhagen',    country: 'Denmark',       schengen: true  }, departureTime: '08:00', arrivalTime: '09:10', aircraft: 'A320' },
  'SK747': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'AMS', city: 'Amsterdam',     country: 'Netherlands',   schengen: true  }, departureTime: '07:40', arrivalTime: '10:00', aircraft: 'A319' },
  'SK683': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'FRA', city: 'Frankfurt',     country: 'Germany',       schengen: true  }, departureTime: '06:50', arrivalTime: '09:00', aircraft: 'A320' },
  'SK501': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'CDG', city: 'Paris',         country: 'France',        schengen: true  }, departureTime: '07:15', arrivalTime: '09:45', aircraft: 'A320' },
  'SK738': { airline: 'SAS', origin: { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' }, destination: { iata: 'HEL', city: 'Helsinki',      country: 'Finland',       schengen: true  }, departureTime: '08:15', arrivalTime: '09:25', aircraft: 'A319' },

  // ── Finnair return flights (inbound to HEL) ─────────────────────────────────
  'AY2':   { airline: 'Finnair', origin: { iata: 'LHR', name: 'London Heathrow',    city: 'London'     }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '12:30', arrivalTime: '17:40', aircraft: 'A350-900' },
  'AY4':   { airline: 'Finnair', origin: { iata: 'LHR', name: 'London Heathrow',    city: 'London'     }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '17:30', arrivalTime: '22:40', aircraft: 'A321' },
  'AY122': { airline: 'Finnair', origin: { iata: 'LHR', name: 'London Heathrow',    city: 'London'     }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '14:30', arrivalTime: '19:40', aircraft: 'A321neo' },
  'AY132': { airline: 'Finnair', origin: { iata: 'LGW', name: 'London Gatwick',     city: 'London'     }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '10:20', arrivalTime: '15:30', aircraft: 'A320' },
  'AY202': { airline: 'Finnair', origin: { iata: 'JFK', name: 'New York JFK',       city: 'New York'   }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '22:00', arrivalTime: '15:00', aircraft: 'A350-900' },
  'AY204': { airline: 'Finnair', origin: { iata: 'JFK', name: 'New York JFK',       city: 'New York'   }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '16:00', arrivalTime: '09:00', aircraft: 'A350-900' },
  'AY402': { airline: 'Finnair', origin: { iata: 'BKK', name: 'Suvarnabhumi',       city: 'Bangkok'    }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '03:25', arrivalTime: '09:00', aircraft: 'A350-900' },
  'AY602': { airline: 'Finnair', origin: { iata: 'NRT', name: 'Tokyo Narita',       city: 'Tokyo'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '11:05', arrivalTime: '15:00', aircraft: 'A350-900' },
  'AY702': { airline: 'Finnair', origin: { iata: 'SIN', name: 'Singapore Changi',   city: 'Singapore'  }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '18:10', arrivalTime: '23:55', aircraft: 'A350-900' },
  'AY712': { airline: 'Finnair', origin: { iata: 'DXB', name: 'Dubai International',city: 'Dubai'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '06:05', arrivalTime: '10:25', aircraft: 'A330-300' },
  'AY722': { airline: 'Finnair', origin: { iata: 'HKG', name: 'Hong Kong Intl',     city: 'Hong Kong'  }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '16:10', arrivalTime: '21:00', aircraft: 'A350-900' },
  'AY802': { airline: 'Finnair', origin: { iata: 'PEK', name: 'Beijing Capital',    city: 'Beijing'    }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '13:20', arrivalTime: '18:00', aircraft: 'A350-900' },
  'AY862': { airline: 'Finnair', origin: { iata: 'ICN', name: 'Seoul Incheon',      city: 'Seoul'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '17:40', arrivalTime: '22:00', aircraft: 'A350-900' },
  'AY902': { airline: 'Finnair', origin: { iata: 'DEL', name: 'Indira Gandhi Intl', city: 'Delhi'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true }, departureTime: '08:00', arrivalTime: '12:30', aircraft: 'A330-300' },

  // ── Finnair codeshares / regional (AY1xxx) ──────────────────────────────────
  'AY1411': { airline: 'Finnair', origin: { iata: 'FRA', name: 'Frankfurt Airport',           city: 'Frankfurt' }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true  }, departureTime: '11:45', arrivalTime: '15:05', aircraft: 'A319', previousGate: 'B14' },
  'AY1413': { airline: 'Finnair', origin: { iata: 'FRA', name: 'Frankfurt Airport',           city: 'Frankfurt' }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true  }, departureTime: '17:30', arrivalTime: '20:50', aircraft: 'A319', previousGate: 'B22' },
  'AY1578': { airline: 'Finnair', origin: { iata: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true  }, departureTime: '14:20', arrivalTime: '18:05', aircraft: 'A321neo', previousGate: '2F12' },
  'AY1580': { airline: 'Finnair', origin: { iata: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris'      }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true  }, departureTime: '19:45', arrivalTime: '23:30', aircraft: 'A321',    previousGate: '2F08' },
  'AY1784': { airline: 'Finnair', origin: { iata: 'VCE', name: 'Venice Marco Polo',        city: 'Venice'     }, destination: { iata: 'HEL', city: 'Helsinki', country: 'Finland', schengen: true  }, departureTime: '11:10', arrivalTime: '14:50', aircraft: 'A320' },

  // ── Lufthansa (LH) departing FRA ────────────────────────────────────────────
  'LH400':  { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'JFK', city: 'New York JFK',  country: 'United States', schengen: false }, departureTime: '10:30', arrivalTime: '13:30', aircraft: 'B747-8',   previousGate: 'B44' },
  'LH404':  { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'JFK', city: 'New York JFK',  country: 'United States', schengen: false }, departureTime: '14:55', arrivalTime: '17:55', aircraft: 'A340-600' },
  'LH456':  { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'LAX', city: 'Los Angeles',   country: 'United States', schengen: false }, departureTime: '11:00', arrivalTime: '13:45', aircraft: 'A380-800' },
  'LH600':  { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'NRT', city: 'Tokyo Narita',  country: 'Japan',         schengen: false }, departureTime: '13:30', arrivalTime: '09:05', aircraft: 'B747-8' },
  'LH760':  { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'DXB', city: 'Dubai',         country: 'UAE',           schengen: false }, departureTime: '14:30', arrivalTime: '22:30', aircraft: 'A321' },
  'LH3306': { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'HEL', city: 'Helsinki',      country: 'Finland',       schengen: true  }, departureTime: '07:00', arrivalTime: '10:10', aircraft: 'A319' },
  'LH3308': { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'HEL', city: 'Helsinki',      country: 'Finland',       schengen: true  }, departureTime: '18:05', arrivalTime: '21:15', aircraft: 'A319' },
  'LH1038': { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'ARN', city: 'Stockholm',     country: 'Sweden',        schengen: true  }, departureTime: '06:50', arrivalTime: '09:10', aircraft: 'A319' },
  'LH4440': { airline: 'Lufthansa', origin: { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' }, destination: { iata: 'AMS', city: 'Amsterdam',     country: 'Netherlands',   schengen: true  }, departureTime: '07:15', arrivalTime: '08:25', aircraft: 'A319' },
};

export async function lookupFlight(rawFlightNumber: string): Promise<FlightInfo | null> {
  const key = rawFlightNumber.trim().toUpperCase();
  await new Promise((r) => setTimeout(r, 400 + Math.random() * 300));
  const entry = ROUTES[key];
  if (!entry) return null;
  return { flightNumber: key, ...entry };
}
